### ISSUE TITLE
BrowserSync issue with newest version - LiveReload isn't there to reload the page

### ISSUE THREAD

**Issue by rekosko** [micromata/generator-bootstrap-kickstart#34]
Hi...

Sorry to bother you once again but I finally thought that everything is nice and working just fine but after updating to latest version `2.1.0` now what I get is another issue:)

I've tested it in my project and in clean installation of `bootstrap-kickstart` and the verdict is that something is wrong:)

After any change in `.js` or `.hbs` files the grunt is picking up the changes and I see in console that it found what and where is changed but it doesn't update the view - live reload isn't kicking in - before whenever I changed it took a second to just refresh the page.

I'm working on Chrome and browsing the site using `http://localhost:3000/` address.

What is funny that when I do any change to `.less` file it's injecting the new style and automatically refreshing my page.

Please verify that `BrowserSync` is not working for `.js` and `.hbs` files on clean installation.

btw: I'm using `grunt sync`

**Comment by mischah** [comment]
No Problem :blush:

Interesting. This might be an error. I’m going to investigate on that soon.

I personally use `grunt` instead of `grunt sync` most of the time.
It also handles live reloading but you need a live-reload browser extension like [LiveReload](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei <https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei>) in companion.

**Comment by mischah** [comment]
No Problem :blush:

Interesting. This might be an error. I’m going to investigate on that soon.

I personally use `grunt` instead of `grunt sync` most of the time.
It also handles live reloading but you need a live-reload browser extension like [LiveReload](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei) in companion.

**Comment by rekosko** [comment]
I've just checked that LiveReload plugin and it's working if I run `grunt` or `grunt sync` and click "Enable LiveReload" in upper right in Chrome browser.

But I really don't want to use the plugin - before it was working like a charm:(

Seems for me like a small issue. Hope you could reproduce and fix it:)

Thanks once again for the quick response!:)

**Comment by rekosko** [comment]
Hi, any updates on this:)?

**Comment by mischah** [comment]
Nope. Sorry. Hope to find some time tonight. But I can’t promise anything :pensive:

**Comment by mischah** [comment]
Hej, there were two errors I fixed with v2.1.1.

I Just published the new version on npm:
https://www.npmjs.com/package/generator-bootstrap-kickstart

It should be available in a matter of minutes :blush: 

Thanks for reporting.
